'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {clientFor,connectWallet,CONTRACT_ADDRESS,Eip1193} from '../../lib/genlayer';
type Service={id?:string|number;service_id?:string|number;service_key?:string;service_name?:string;service_domain?:string;policy_version?:string|number;policy_status?:string;source_urls?:unknown[]};
const parse=(raw:string):Service=>{try{return JSON.parse(raw)}catch{return {name:raw}}};
export default function Services(){
 const[rows,setRows]=useState<Service[]>([]),[state,setState]=useState('LOADING POLICY REGISTRY…');
 const load=async()=>{try{const p=(window as Window&{ethereum?:Eip1193}).ethereum;if(!p){setState('CONNECT A WALLET TO READ CANONICAL SERVICES.');return}const a=await connectWallet(p),c=clientFor(a as `0x${string}`,p);const result=await c.readContract({address:CONTRACT_ADDRESS as `0x${string}`,functionName:'get_services',args:[0n,50n] as never[]}) as string[];setRows((result||[]).map(parse));setState(result?.length?'':'NO SERVICES REGISTERED YET.')}catch(e){setState(e instanceof Error?e.message:'CANONICAL READ FAILED')}};
 useEffect(()=>{const timer=window.setTimeout(load,0);return()=>window.clearTimeout(timer)},[]);
 return <div className="shell"><p className="kicker">REGISTRY / SERVICES</p><div className="page-heading"><div><h1>Services</h1><p className="lede">Policies currently riding the rail.</p></div><Link className="button primary" href="/services/new">+ REGISTER SERVICE</Link></div>{state!=='LOADING POLICY REGISTRY…'&&<div className={rows.length?'notice':'empty-state'}><h2>{rows.length?'LIVE POLICY BOARD':state}</h2>{!rows.length&&<p>{state.includes('FAILED')?'Try again after checking your wallet and network.':'Register your first service to start tracking policy state.'}</p>}</div>}<div className="service-grid">{rows.map((s,i)=>{const id=s.id??s.service_id??i;return <article className="panel service-card" key={`${s.service_key??id}`}><div className="panel-title"><span>{s.service_key??`SERVICE ${id}`}</span><span className="mono">/{id}</span></div><h2>{s.service_name??'Unnamed service'}</h2><p className="muted">{s.service_domain??'Domain unavailable'}</p><div className="dimension"><span>POLICY STATUS</span><strong className="proceed">{s.policy_status??'UNKNOWN'}</strong></div><div className="dimension"><span>VERSION</span><span className="mono">{s.policy_version??'—'}</span></div><div className="dimension"><span>SOURCES</span><span>{Array.isArray(s.source_urls)?s.source_urls.length:'—'}</span></div><Link className="text-link" href={`/service/${id}`}>OPEN SERVICE →</Link></article>})}</div></div>;
}
