import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {resolveActionId,resolveServiceId,resolvePlanId,assertSuccessfulExecution} from '../lib/genlayer';

describe('canonical creation links',()=>{
 it('resolves and renders the canonical service ID without claiming verification',()=>{const rows=['{"service_key":"new-service","id":17}'];expect(resolveServiceId(rows,'new-service')).toBe(17);const source=readFileSync('app/services/new/page.tsx','utf8');expect(source).toContain('OPEN SERVICE →');expect(source).toContain('/service/${canonicalId}');expect(source).toContain('CANONICAL STATE FOUND · EXECUTION VERIFICATION STILL SYNCING')});
 it('resolves and renders the nested canonical action ID without claiming verification',()=>{const rows=['{"id":23,"service_id":"11","spec":{"action_key":"new-action","action_type":"API_CALL"}}'];expect(resolveActionId(rows,'new-action','11')).toBe(23);const source=readFileSync('app/action/new/page.tsx','utf8');expect(source).toContain('OPEN ACTION →');expect(source).toContain('/action/${canonicalId}');expect(source).toContain('CANONICAL STATE FOUND · EXECUTION VERIFICATION STILL SYNCING')});
 it('resolves a new plan by complete canonical identity rather than title alone',()=>{const rows=['{"plan_id":"2","creator":"0x1","title":"Same","description":"old","steps":[]}','{"plan_id":"7","creator":"0x1","title":"Same","description":"new","steps":[{"service_id":"1","action_id":"2","required":true}]}'];expect(resolvePlanId(rows,{creator:'0x1',title:'Same',description:'new',steps:[{service_id:'1',action_id:'2',required:true}]})).toBe('7');const source=readFileSync('app/plans/new/page.tsx','utf8');expect(source).toContain('resolvePlanId');expect(source).toContain('/plans/${id}')});
 it('accepts only FINISHED_WITH_RETURN as verified and preserves explicit failure',()=>{expect(()=>assertSuccessfulExecution('FINISHED_WITH_RETURN')).not.toThrow();expect(()=>assertSuccessfulExecution('FINISHED_WITH_ERROR')).toThrow('FINISHED_WITH_ERROR');expect(()=>assertSuccessfulExecution(undefined)).toThrow('UNKNOWN')});
 it('wires canonical v2 plan, escrow, receipt and activity reads',()=>{expect(readFileSync('app/plans/[id]/page.tsx','utf8')).toContain("get_plan");expect(readFileSync('app/escrow/page.tsx','utf8')).toContain("get_escrows");expect(readFileSync('app/receipts/page.tsx','utf8')).toContain("get_receipts");expect(readFileSync('app/receipts/[id]/page.tsx','utf8')).toContain('receipt.status');const activity=readFileSync('app/activity/page.tsx','utf8');expect(activity).toContain('aggregateActivityEvents');expect(activity).toContain('get_completions');expect(activity).toContain('get_disputes')});
 it('uses completion and dispute IDs for escrow adjudication controls',()=>{const source=readFileSync('app/escrow/[id]/page.tsx','utf8');expect(source).toContain('get_completions');expect(source).toContain("adjudicate_completion',[completionId]");expect(source).toContain('adjudicate_dispute');expect(source).toContain('resolve_dispute')});
 it('exposes canonical evidence and guarded settlement controls',()=>{const source=readFileSync('app/escrow/[id]/page.tsx','utf8');expect(source).toContain('CANONICAL OUTCOME');expect(source).toContain('COMPLETION ADJUDICATION');expect(source).toContain('DISPUTE ADJUDICATION');expect(source).toContain("outcome!=='RELEASE'");expect(source).toContain("outcome==='REFUND'");expect(source).toContain('EXECUTING CANONICAL OUTCOME');expect(source).toContain('get_dispute');});
});
