import {describe,it,expect} from 'vitest';
import {connectWallet,assertSuccessfulExecution,normalizeExecutionResult,waitForFinalizedReceipt,waitForExecutionResult,resolveServiceId,resolveActionId,readAllRecords,validateActionInvariants,verifyChangeHistoryAdvance,verifySnapshotAdvance,verifyAuthorizationAdvance,resolveContractAddress,FROZEN_TERMSRAIL_CONTRACT,booleanLike} from '../lib/genlayer';
describe('wallet finality prerequisites',()=>{
  it('requests accounts and accepts Studionet',async()=>{const calls:string[]=[];const p={request:async({method}:{method:string})=>{calls.push(method);return method==='eth_requestAccounts'?['0xabc']:'0xf22f'}};await expect(connectWallet(p)).resolves.toBe('0xabc');expect(calls).toEqual(['eth_requestAccounts','eth_chainId'])});
  it('switches a wrong network',async()=>{const calls:string[]=[];const p={request:async({method}:{method:string})=>{calls.push(method);return method==='eth_requestAccounts'?['0xabc']:method==='eth_chainId'?'0x1':null}};await connectWallet(p);expect(calls).toContain('wallet_switchEthereumChain')});
  it('rejects when wallet returns no account',async()=>{const p={request:async({method}:{method:string})=>method==='eth_requestAccounts'?[]:'0xf22f'};await expect(connectWallet(p)).resolves.toBe('')});
});
describe('canonical safety helpers',()=>{
  it('requires the exact successful execution result',()=>{expect(()=>assertSuccessfulExecution('FINISHED_WITH_RETURN')).not.toThrow();for(const value of ['ERROR','RETURN',undefined,'unexpected'])expect(()=>assertSuccessfulExecution(value)).toThrow()});
  it('normalizes StudioNet receipt execution result shapes',()=>{const ok=[{txExecutionResultName:'FINISHED_WITH_RETURN'},{txExecutionResult:1},{tx_execution_result_name:'FINISHED_WITH_RETURN'},{consensus_data:{leader_receipt:[{execution_result:1}]}},{data:{genvm_result:{execution_result:'FINISHED_WITH_RETURN'}}}];for(const receipt of ok){expect(normalizeExecutionResult(receipt)).toBe('FINISHED_WITH_RETURN');expect(()=>assertSuccessfulExecution(receipt)).not.toThrow()}expect(normalizeExecutionResult({consensus_data:{leader_receipt:[{execution_result:0},{execution_result:1}]}})).toBe('FINISHED_WITH_RETURN');expect(normalizeExecutionResult({consensus_data:{leader_receipt:[{execution_result:0},{execution_result:2}]}})).toBe('FINISHED_WITH_ERROR');for(const receipt of [{txExecutionResult:2},{foo:'bar'},{}])expect(()=>assertSuccessfulExecution(receipt)).toThrow()});
  it('waits through ACCEPTED until FINALIZED without treating accepted as final',async()=>{let reads=0;const client={waitForTransactionReceipt:async()=>({status:5}),getTransaction:async()=>({status:++reads>1?7:5})};await expect(waitForFinalizedReceipt(client,'0xabc',0,3)).resolves.toMatchObject({status:7});expect(reads).toBe(2)});
  it('hydrates execution result after finalized receipt',async()=>{let reads=0;const client={getTransaction:async()=>++reads===1?{foo:'pending'}:{consensus_data:{leader_receipt:[{execution_result:1}]}}};await expect(waitForExecutionResult(client,'0xabc',{status:7},0,3)).resolves.toBe('FINISHED_WITH_RETURN')});
  it('always selects a valid configured or frozen contract address',()=>{const configured='0x1111111111111111111111111111111111111111';expect(resolveContractAddress(configured)).toBe(configured);for(const value of [undefined,'','  ','not-an-address','0x123'])expect(resolveContractAddress(value)).toBe(FROZEN_TERMSRAIL_CONTRACT)});
  it('fails after the bounded finality window',async()=>{const client={waitForTransactionReceipt:async()=>({status:5}),getTransaction:async()=>({status:5})};await expect(waitForFinalizedReceipt(client,'0xabc',0,2)).rejects.toThrow('Timed out')});
  it('resolves service IDs by canonical service key',()=>{const rows=['{"service_key":"other","id":4}','{"service_key":"target","service_id":"9"}'];expect(resolveServiceId(rows,'target')).toBe('9');expect(resolveServiceId(rows,'missing')).toBeUndefined()});
  it('resolves nested deployed action IDs and reads beyond the first 50 records',async()=>{expect(resolveActionId(['{"id":"2","service_id":"11","spec":{"action_key":"target","action_type":"API_CALL"}}'],'target')).toBe('2');const pages=[Array.from({length:50},(_,i)=>String(i)),['tail']];const rows=await readAllRecords(async offset=>pages[Number(offset/50n)]??[]);expect(rows).toHaveLength(51)});
  it('normalizes canonical boolean-like execution values',()=>{expect(booleanLike('True')).toBe(true);expect(booleanLike('False')).toBe(false);expect(booleanLike(true)).toBe(true);expect(booleanLike(false)).toBe(false)});
  it('enforces deterministic action invariants',()=>{expect(validateActionInvariants('MODEL_TRAINING',{model_training:'NO'})).toBeTruthy();expect(validateActionInvariants('MODEL_TRAINING',{model_training:'YES'})).toBeUndefined();expect(validateActionInvariants('API_CALL',{automation:'NO'})).toBeTruthy()});
  it('mirrors DATA_COLLECTION invariant branches',()=>{expect(validateActionInvariants('DATA_COLLECTION',{automation:'NO',scraping:'NO',bulk_collection:'NO'})).toContain('DATA_COLLECTION');for(const key of ['automation','scraping','bulk_collection'])expect(validateActionInvariants('DATA_COLLECTION',{automation:'NO',scraping:'NO',bulk_collection:'NO',[key]:'YES'})).toBeUndefined()});
  it('verifies method-specific canonical readback',()=>{const service={policy_version:1};expect(verifySnapshotAdvance(service,{policy_version:2})).toBe(true);const unchanged=['{"change_state":"UNCHANGED"}'];expect(verifyChangeHistoryAdvance(unchanged,[...unchanged,'{"change_state":"NON_MATERIAL_CHANGE"}'])).toBe(true);expect(verifyChangeHistoryAdvance(unchanged,unchanged)).toBe(false);expect(verifyAuthorizationAdvance('{"action_id":"1","sequence":1,"policy_version":2}','{"action_id":"1","sequence":2,"policy_version":2}','1',2)).toBe(true);expect(verifyAuthorizationAdvance('{"action_id":"1","sequence":2,"policy_version":2}','{"action_id":"1","sequence":2,"policy_version":2}','1',2)).toBe(false)});
});
