import {describe,it,expect} from 'vitest';
import {connectWallet,assertSuccessfulExecution,resolveServiceId,resolveActionId,readAllRecords,validateActionInvariants,verifyChangeHistoryAdvance,verifySnapshotAdvance,verifyAuthorizationAdvance} from '../lib/genlayer';
describe('wallet finality prerequisites',()=>{
  it('requests accounts and accepts Studionet',async()=>{const calls:string[]=[];const p={request:async({method}:{method:string})=>{calls.push(method);return method==='eth_requestAccounts'?['0xabc']:'0xf22f'}};await expect(connectWallet(p)).resolves.toBe('0xabc');expect(calls).toEqual(['eth_requestAccounts','eth_chainId'])});
  it('switches a wrong network',async()=>{const calls:string[]=[];const p={request:async({method}:{method:string})=>{calls.push(method);return method==='eth_requestAccounts'?['0xabc']:method==='eth_chainId'?'0x1':null}};await connectWallet(p);expect(calls).toContain('wallet_switchEthereumChain')});
  it('rejects when wallet returns no account',async()=>{const p={request:async({method}:{method:string})=>method==='eth_requestAccounts'?[]:'0xf22f'};await expect(connectWallet(p)).resolves.toBe('')});
});
describe('canonical safety helpers',()=>{
  it('requires the exact successful execution result',()=>{expect(()=>assertSuccessfulExecution('FINISHED_WITH_RETURN')).not.toThrow();for(const value of ['ERROR','RETURN',undefined,'unexpected'])expect(()=>assertSuccessfulExecution(value)).toThrow()});
  it('resolves service IDs by canonical service key',()=>{const rows=['{"service_key":"other","id":4}','{"service_key":"target","service_id":"9"}'];expect(resolveServiceId(rows,'target')).toBe('9');expect(resolveServiceId(rows,'missing')).toBeUndefined()});
  it('resolves action IDs and reads beyond the first 50 records',async()=>{expect(resolveActionId(['{"action_key":"target","id":"88"}'],'target')).toBe('88');const pages=[Array.from({length:50},(_,i)=>String(i)),['tail']];const rows=await readAllRecords(async offset=>pages[Number(offset/50n)]??[]);expect(rows).toHaveLength(51)});
  it('enforces deterministic action invariants',()=>{expect(validateActionInvariants('MODEL_TRAINING',{model_training:'NO'})).toBeTruthy();expect(validateActionInvariants('MODEL_TRAINING',{model_training:'YES'})).toBeUndefined();expect(validateActionInvariants('API_CALL',{automation:'NO'})).toBeTruthy()});
  it('mirrors DATA_COLLECTION invariant branches',()=>{expect(validateActionInvariants('DATA_COLLECTION',{automation:'NO',scraping:'NO',bulk_collection:'NO'})).toContain('DATA_COLLECTION');for(const key of ['automation','scraping','bulk_collection'])expect(validateActionInvariants('DATA_COLLECTION',{automation:'NO',scraping:'NO',bulk_collection:'NO',[key]:'YES'})).toBeUndefined()});
  it('verifies method-specific canonical readback',()=>{const service={policy_version:1};expect(verifySnapshotAdvance(service,{policy_version:2})).toBe(true);const unchanged=['{"change_state":"UNCHANGED"}'];expect(verifyChangeHistoryAdvance(unchanged,[...unchanged,'{"change_state":"NON_MATERIAL_CHANGE"}'])).toBe(true);expect(verifyChangeHistoryAdvance(unchanged,unchanged)).toBe(false);expect(verifyAuthorizationAdvance('{"action_id":"1","sequence":1,"policy_version":2}','{"action_id":"1","sequence":2,"policy_version":2}','1',2)).toBe(true);expect(verifyAuthorizationAdvance('{"action_id":"1","sequence":2,"policy_version":2}','{"action_id":"1","sequence":2,"policy_version":2}','1',2)).toBe(false)});
});
